"""Redo migrations

Revision ID: 023e3f19f5e0
Revises: 
Create Date: 2025-05-17 02:26:39.686927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023e3f19f5e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('RoutineStatus', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='routinestatus'), nullable=False),
    sa.Column('created_for', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('RoutineEnum', sa.Enum('WORKOUT', 'DIETARY', name='routineenum'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['created_for'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routine_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('ItemType', sa.Enum('EXERCISE_ITEM', 'MEAL_OPT_ITEM', name='itemtype'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('min_sets', sa.Integer(), nullable=False),
    sa.Column('max_sets', sa.Integer(), nullable=True),
    sa.Column('set_duration', sa.Time(), nullable=False),
    sa.Column('set_interval', sa.Time(), nullable=False),
    sa.Column('min_reps', sa.Integer(), nullable=True),
    sa.Column('max_reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['id'], ['routine_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_items')
    op.drop_table('routine_items')
    op.drop_table('routines')
    # ### end Alembic commands ###
