"""Add professor_id to StudentRole

Revision ID: 0527268adbaa
Revises: 3d728594022f
Create Date: 2025-05-02 00:53:50.153885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0527268adbaa'
down_revision = '3d728594022f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'professors', ['supervisor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supervisor_id')

    # ### end Alembic commands ###
