"""Fix routine enums

Revision ID: 0f4e442083aa
Revises: 17486cf05a07
Create Date: 2025-05-18 19:14:24.661176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f4e442083aa'
down_revision = '17486cf05a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='routinestatus'), nullable=False))
        batch_op.add_column(sa.Column('type', sa.Enum('WORKOUT', 'DIETARY', name='routineenum'), nullable=False))
        batch_op.drop_column('RoutineEnum')
        batch_op.drop_column('RoutineStatus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RoutineStatus', mysql.ENUM('PENDING', 'APPROVED', 'REJECTED'), nullable=False))
        batch_op.add_column(sa.Column('RoutineEnum', mysql.ENUM('WORKOUT', 'DIETARY'), nullable=False))
        batch_op.drop_column('type')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
