"""Fix item type

Revision ID: 17486cf05a07
Revises: 77517f323bd5
Create Date: 2025-05-18 19:13:39.510727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17486cf05a07'
down_revision = '77517f323bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('WORKOUT', 'DIET', name='itemtype'), nullable=False))
        batch_op.drop_column('ItemType')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ItemType', mysql.ENUM('EXERCISE_ITEM', 'MEAL_OPT_ITEM'), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
