"""Remove Roles, add Majors

Revision ID: 644b031046f4
Revises: 0527268adbaa
Create Date: 2025-05-04 19:58:40.827553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '644b031046f4'
down_revision = '0527268adbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    op.drop_table('students')
    op.drop_table('professors')
    op.drop_table('roles')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RoleEnum', sa.Enum('USER', 'ADMIN', 'GOD', name='roleenum'), nullable=False, comment="User's role in the system."))
        batch_op.add_column(sa.Column('supervisor_id', sa.String(length=36), nullable=True, comment="Supervisor's ID for student's users who want to suggest diets and workouts."))
        batch_op.create_foreign_key(None, 'profiles', ['supervisor_id'], ['id'])
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=20), nullable=False, comment='Role of the user'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supervisor_id')
        batch_op.drop_column('RoleEnum')

    op.create_table('professors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['roles.id'], name='professors_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('profile_id', mysql.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='roles_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('students',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('supervisor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['roles.id'], name='students_ibfk_1'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['professors.id'], name='students_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admins',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['roles.id'], name='admins_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
