"""Fix items

Revision ID: 77517f323bd5
Revises: 023e3f19f5e0
Create Date: 2025-05-18 18:09:16.866048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77517f323bd5'
down_revision = '023e3f19f5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('min_sets', sa.Integer(), nullable=False),
    sa.Column('max_sets', sa.Integer(), nullable=True),
    sa.Column('set_duration', sa.Time(), nullable=False),
    sa.Column('set_interval', sa.Time(), nullable=False),
    sa.Column('min_reps', sa.Integer(), nullable=True),
    sa.Column('max_reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['routine_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exercise_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_items',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('exercise_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('min_sets', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('max_sets', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('set_duration', mysql.TIME(), nullable=False),
    sa.Column('set_interval', mysql.TIME(), nullable=False),
    sa.Column('min_reps', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('max_reps', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('weight', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='exercise_items_ibfk_1'),
    sa.ForeignKeyConstraint(['id'], ['routine_items.id'], name='exercise_items_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('item_exercises')
    # ### end Alembic commands ###
