"""Add Major

Revision ID: a1646c438e7e
Revises: 644b031046f4
Create Date: 2025-05-04 23:14:33.903362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1646c438e7e'
down_revision = '644b031046f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('majors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('university', sa.String(length=50), nullable=False),
    sa.Column('AreaTags', sa.Enum('OTHER', 'NUTRI', 'PE', name='areatags'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_majors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('college_code', sa.String(length=50), nullable=False),
    sa.Column('MajorEnum', sa.Enum('STUDENT', 'PROFESSOR', name='majorenum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_majors')
    op.drop_table('majors')
    # ### end Alembic commands ###
