"""Add friend request notifications

Revision ID: d1df0e507cd1
Revises: 4f38b52d1120
Create Date: 2025-04-27 20:40:37.242829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1df0e507cd1'
down_revision = '4f38b52d1120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_request_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=True, comment='ID of the user profile sending the notification'),
    sa.Column('friendship_id', sa.Integer(), nullable=False, comment='ID of the friendship'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='URL to redirect when the notification is clicked'),
    sa.ForeignKeyConstraint(['friendship_id'], ['friendships.id'], ),
    sa.ForeignKeyConstraint(['id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('notifications_ibfk_2', type_='foreignkey')
        batch_op.drop_column('url')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', mysql.VARCHAR(length=36), nullable=True, comment='ID of the user profile sending the notification'))
        batch_op.add_column(sa.Column('url', mysql.VARCHAR(length=255), nullable=True, comment='URL to redirect when the notification is clicked'))
        batch_op.create_foreign_key('notifications_ibfk_2', 'profiles', ['sender_id'], ['id'])

    op.drop_table('friend_request_notifications')
    # ### end Alembic commands ###
