"""Update ItemExercises

Revision ID: fe7570be11b6
Revises: 0f4e442083aa
Create Date: 2025-05-19 02:30:26.887169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe7570be11b6'
down_revision = '0f4e442083aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('muscle_group',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('item_exercises', schema=None) as batch_op:
        batch_op.alter_column('set_duration',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('set_interval',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('min_reps',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_exercises', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('min_reps',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('set_interval',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('set_duration',
               existing_type=mysql.TIME(),
               nullable=False)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('muscle_group',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
